### ISSUE TITLE
Some errors 

### ISSUE THREAD

**Issue by hbokh** [urt30plus/b3#3]
Thanks for this great B3 version in Python3! 👍🏻

FYI Here are some errors being logged (`log_level: 40` - errors):

```
2024-12-08 12:24:52,864 ERROR    [MainThread] Could not start plugin poweradminurt
Traceback (most recent call last):
  File "/home/hbokh/b3/b3/parser.py", line 560, in startPlugins
    plugin.onStartup()
  File "/home/hbokh/b3/b3/plugins/poweradminurt/iourt43.py", line 223, in onStartup
    self._origvote = self.console.getCvar("g_allowvote").getInt()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'getInt'
```
Even though it says "not start plugin poweradminurt", the pa-commands do work. 

This one is from file `b3/plugins/hof.py`:
```
2024-12-08 12:32:43,034 ERROR    [knifer] Query failed [INSERT INTO plugin_hof(plugin_name, map_name, player_id, score) VALUES('knifer', 'ut4_gad_dom_ls', 0, 2)] None: UNIQUE constraint failed: plugin_hof.plugin_name, plugin_hof.map_name
```

**Comment by hbokh** [comment]
Fix for `b3/plugins/hof.py` and the `UNIQUE constraint failed`.
If you want to overwrite the existing row, use `INSERT OR REPLACE`:

```
    except LookupError:
        q = (
            f"INSERT OR REPLACE INTO plugin_hof(plugin_name, map_name, player_id, score) "
            f"VALUES('{plugin_name}', '{map_name}', {client.id}, {score})"
            ""
        )
```

This replaces the existing row with the new one.

For the `poweradminurt` issue, somehow raising the RCON timeout values did the trick:

```
rcon_timeout: 0.8
rcon_timeout2: 0.4
```
